steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,USE_FIRESTORE=true
      - --set-secrets=SESSION_SECRET=nexus-session-secret:latest,PAYMENT_WEBHOOK_SECRET=nexus-payment-webhook-secret:latest
substitutions:
  _REGION: asia-southeast1
  _REPOSITORY: nexus
  _SERVICE: nexus-kinetic
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
options:
  logging: CLOUD_LOGGING_ONLY
